// <auto-generated />
namespace BizzDesk_Leap_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrate8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate8));
        
        string IMigrationMetadata.Id
        {
            get { return "201707271113041_migrate-8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
